ALTER TABLE driver_matches
    ADD COLUMN dropoff_lat DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN dropoff_lng DOUBLE PRECISION NOT NULL DEFAULT 0;

ALTER TABLE driver_matches ALTER COLUMN dropoff_lat DROP DEFAULT;
ALTER TABLE driver_matches ALTER COLUMN dropoff_lng DROP DEFAULT;
